version: '3.7'

services:
  # NGINX - Service
  webserver:
    image: nginx:alpine
    container_name: dev-webserver
    working_dir: /application
    restart: unless-stopped
    volumes:
      - .:/application
      - ./docker-manifest/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      testing_net:
        ipv4_address: 192.24.1.3

  # PHP-FPM - Service
  php-fpm:
    build: .
    container_name: dev
    working_dir: /application
    volumes:
      - .:/application
      - ./docker-manifest/php-fpm/php-ini-overrides.ini:/etc/7.4/fpm/conf.d/99-overrides.ini
    networks:
      testing_net:
        ipv4_address: 192.24.1.4


  # MariaDB - Service
  db:
    image: mariadb:latest
    container_name: dev-mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./docker-manifest/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      testing_net:
        ipv4_address: 192.24.1.5

# Volumes
volumes:
  mariadbdata:
    driver: local

# Networks
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 192.24.0.0/16
